### ISSUE TITLE
Didn't work on a server

### ISSUE THREAD

**Issue by Bluewolf1942** [HeyImAmethyst/FairyFactionsRevived#1]
Hey so I tried to add this mod onto my server cause I used to love it on 1.7 but it didn't seem to work, the server wouldn't load and flagged it like it does when I put mods that are only client side into the server (such as Neat or Optifine). The mod doesn't work though without being in the server. Not sure why it's flagging as client side but if this can be sorted I would greatly appreciate it I would love to play this mod with my friends!

**Comment by HeyImAmethyst** [comment]
> Hey so I tried to add this mod onto my server cause I used to love it on 1.7 but it didn't seem to work, the server wouldn't load and flagged it like it does when I put mods that are only client side into the server (such as Neat or Optifine). The mod doesn't work though without being in the server. Not sure why it's flagging as client side but if this can be sorted I would greatly appreciate it I would love to play this mod with my friends!

Hello! Thank you for bringing this to my attention! So it seemed I had put some code in places where it shouldn't be. I refactored some of the code so that the mod can work on a server and it seems to work now. I'm going to put out an update soon with the bug fix!

**Comment by Bluewolf1942** [comment]
> 

It works! Thank you so so much so excited to finally be playing this mod again!!
